version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: lmmseval/blogs:slim
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
